"""After editing config.js run:  python3 sync-head.py
Writes the page title, link-preview (WhatsApp/Instagram) tags and favicon from config.js.
Link previews need "siteUrl" in config.js to be your real, full GitHub Pages address.
og.jpg (the picture in the preview card) is a plain static file and is deliberately generic,
so it is NOT regenerated by this script and does not need to change per gym."""
import json, re, html, pathlib
R = pathlib.Path(__file__).parent
G = json.loads(re.search(r'window\.GYM\s*=\s*(\{.*\})\s*;?\s*$', (R / 'config.js').read_text(), re.S).group(1))
url = G['siteUrl'].rstrip('/') + '/' if G.get('siteUrl') else ''
e = html.escape
title = f"{G['name']} | Gym in {G['area']}, Bareilly"
desc = f"{G['name']} in {G['area']}, Bareilly. Book a free trial, meet the trainers, get a plan built around you."
head = f'''<!--head-sync-->
<title>{e(title)}</title>
<meta name="description" content="{e(desc)}">
<meta property="og:type" content="website">
<meta property="og:title" content="{e(title)}">
<meta property="og:description" content="{e(desc)}">
<meta property="og:image" content="{url}og.jpg">
<meta property="og:url" content="{url}">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<!--/head-sync-->'''
p = R / 'index.html'
p.write_text(re.sub(r'<!--head-sync-->.*?<!--/head-sync-->', lambda m: head, p.read_text(), flags=re.S))
(R / 'favicon.svg').write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#000"/><text x="32" y="47" font-size="40" font-family="Arial Black,Arial,sans-serif" font-weight="900" text-anchor="middle" fill="#fff">{e(G["name"][:1].upper())}</text></svg>')
print('head + favicon updated for', G['name'])
